version: "3"
services: 
  mariadb:
    image: pierre/mariadb
    volumes:
      - mysqlpersist:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: stage123
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:8080"
  drupal:
    image: drupal
    ports:
      - "81:81"

volumes:
  mysqlpersist:
