version: "3"
services: 
  mariadb:
    image: pierre/mariadb
    volumes:
      - mysqlpersist:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: stage123
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
  drupal:
    image: drupal
    ports:
      - "80:80"
    volumes:
      - phppersist:/var/lib/phpmyadmin

volumes:
  mysqlpersist:
  phppersist:
