version: "3"
services: 
  mariadb:
    image: pierre/mariadb
    volumes:
      - mysqlpersist:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: stage123
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
  drupal:
    image: drupal
    ports:
      - "80:80"
    volumes:
      - modules_persist:/var/www/html/modules
      - profiles_persist:/var/www/html/profiles
      - themes_persist:/var/www/html/themes
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - sites_persist:/var/www/html/sites
  php:
    image: php:7.0-apache
    ports: 
      - "8081:80"
    volumes: 
      - /root/formation/formation/files:/var/www/html

volumes:
  mysqlpersist:
  phppersist:
  modules_persist:
  profiles_persist:
  themes_persist:
  sites_persist: